"""Initial parking management schema

Revision ID: 304d51150194
Revises: 
Create Date: 2026-09-23 10:29:11.852843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304d51150194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_area_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parking_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('daily_maximum', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('overnight_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lost_ticket_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('flat_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('base_duration_minutes > 0 AND grace_period_minutes >= 0', name='ck_rate_minutes'),
    sa.CheckConstraint('base_fee >= 0 AND hourly_rate >= 0', name='ck_rate_nonnegative'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parking_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_rates_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_rates_vehicle_type_id'), ['vehicle_type_id'], unique=False)

    op.create_table('parking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('slot_type', sa.String(length=30), nullable=False),
    sa.Column('allowed_vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('AVAILABLE','OCCUPIED','RESERVED','MAINTENANCE','DISABLED')", name='ck_slot_status'),
    sa.ForeignKeyConstraint(['allowed_vehicle_type_id'], ['vehicle_types.id'], ),
    sa.ForeignKeyConstraint(['area_id'], ['parking_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_slots_allowed_vehicle_type_id'), ['allowed_vehicle_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_slots_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_slots_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_parking_slots_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource'), ['resource'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=120), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_plate_number'), ['plate_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_vehicles_vehicle_type_id'), ['vehicle_type_id'], unique=False)

    op.create_table('parking_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=40), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('attendant_id', sa.Integer(), nullable=False),
    sa.Column('parking_rate_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("payment_status IN ('UNPAID','PAID','VOID')", name='ck_payment_status'),
    sa.CheckConstraint("status IN ('ACTIVE','PAYMENT_PENDING','COMPLETED','CANCELLED')", name='ck_session_status'),
    sa.ForeignKeyConstraint(['attendant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parking_rate_id'], ['parking_rates.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parking_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_sessions_attendant_id'), ['attendant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_sessions_entry_time'), ['entry_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_sessions_exit_time'), ['exit_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_sessions_parking_rate_id'), ['parking_rate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_sessions_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_sessions_slot_id'), ['slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_sessions_ticket_number'), ['ticket_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_parking_sessions_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index('ix_session_slot_status', ['slot_id', 'status'], unique=False)
        batch_op.create_index('ix_session_vehicle_status', ['vehicle_id', 'status'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=40), nullable=False),
    sa.Column('parking_session_id', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('processed_by_id', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint('amount_due >= 0 AND amount_paid >= amount_due AND change_amount >= 0', name='ck_payment_amounts'),
    sa.ForeignKeyConstraint(['parking_session_id'], ['parking_sessions.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parking_session_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_method_id'), ['payment_method_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_processed_by_id'), ['processed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_receipt_number'), ['receipt_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_payments_processed_by_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_method_id'))
        batch_op.drop_index(batch_op.f('ix_payments_paid_at'))

    op.drop_table('payments')
    with op.batch_alter_table('parking_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_vehicle_status')
        batch_op.drop_index('ix_session_slot_status')
        batch_op.drop_index(batch_op.f('ix_parking_sessions_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_parking_sessions_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_parking_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_parking_sessions_slot_id'))
        batch_op.drop_index(batch_op.f('ix_parking_sessions_payment_status'))
        batch_op.drop_index(batch_op.f('ix_parking_sessions_parking_rate_id'))
        batch_op.drop_index(batch_op.f('ix_parking_sessions_exit_time'))
        batch_op.drop_index(batch_op.f('ix_parking_sessions_entry_time'))
        batch_op.drop_index(batch_op.f('ix_parking_sessions_attendant_id'))

    op.drop_table('parking_sessions')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vehicle_type_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_plate_number'))
        batch_op.drop_index(batch_op.f('ix_vehicles_customer_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_slots_status'))
        batch_op.drop_index(batch_op.f('ix_parking_slots_code'))
        batch_op.drop_index(batch_op.f('ix_parking_slots_area_id'))
        batch_op.drop_index(batch_op.f('ix_parking_slots_allowed_vehicle_type_id'))

    op.drop_table('parking_slots')
    with op.batch_alter_table('parking_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_rates_vehicle_type_id'))
        batch_op.drop_index(batch_op.f('ix_parking_rates_is_active'))

    op.drop_table('parking_rates')
    op.drop_table('vehicle_types')
    op.drop_table('system_settings')
    op.drop_table('roles')
    op.drop_table('payment_methods')
    op.drop_table('parking_areas')
    # ### end Alembic commands ###
